/*temp file full of build info, generated by tools/gen_build_info.py.
Contents in this file are not copyrighted material unless obtained
from a copyrighted source*/
#pragma once
#define BUILD_UNIX_TIME 1422459122L
#define BUILD_NUMBER 12L
#define BUILD_DATE 735626L
#define BUILD_USERNAME "mfosdick"
#define BUILD_GIT_BRANCH "master-dev"
#define BUILD_NAME "Boron Silicate"
#define BUILD_FORMULA "B₂(SiO₃)₃"
#define BUILD_FULL_NAME "Boron Silicate (B₂(SiO₃)₃)"
