/*temp file full of build info, generated by tools/gen_build_info.py.
Contents in this file are not copyrighted material unless obtained
from a copyrighted source*/
#pragma once
#define BUILD_UNIX_TIME 1404858076L
#define BUILD_USERNAME "mfosdick"
#define BUILD_GIT_BRANCH "master-dev"
